### ISSUE TITLE
Add `unplug` command

### ISSUE THREAD

**Issue by drasko** [mainflux/bashflux#18]
`unplug` command equivalent to `plug` is missing, but exists in the [mainflux-manager](https://github.com/mainflux/mainflux-manager/blob/master/api/server.go).

**Comment by manuIO** [comment]
fixed here: https://github.com/mainflux/mainflux-cli/pull/19/commits/748fd14001814a54f0b72dfbb57d3a81861605ca

**Comment by nmarcetic** [comment]
LGTM!

**Comment by manuIO** [comment]
can be closed
