### ISSUE TITLE
Wrong lnk in the readme file

### ISSUE THREAD

**Issue by chombium** [mainflux/bashflux#28]
Hi,

I have noticed that the in the "here" link in [README.md](https://github.com/mainflux/bashflux/blame/master/README.md#L37) points to mainflux.io

Best Regards,
Jovan

**Comment by drasko** [comment]
Wrong, and should be changed - documentation moved to Read The Docs. Can you please post a PR?

**Comment by chombium** [comment]
@drasko sure, I'll do that by the end of the day

**Comment by chombium** [comment]
seems like @janko-isidorovic was faster than me :)
61ed1b0 fixes this problem.

**Comment by drasko** [comment]
@chombium thanks anyway for rising the error.
